### ISSUE TITLE
Per variable TM order

### ISSUE THREAD

**Issue by mforets** [agerlach/Flowstar.jl#16]
The example in Sec 3 of https://home.cs.colorado.edu/~xich8622/manual/manual-2.0.0.pdf allows to pass min/max order per variable as in `adaptive orders { min { Ii :4 , G :4} , max { Ii :6 , G :6} }` but I think this is currently not supported.

**Comment by agerlach** [comment]
I was able to abstract `AdaptiveTMOrder` for a flexible API for state-dependent TM orders

See test for various usages

    @test Flowstar._order_string(AdaptiveTMOrder( ("x"=>2, "y" =>3, "z" => 4), ("x"=>20, "y" =>30, "z" => 40))) == 
            Flowstar._order_string(AdaptiveTMOrder( ["x"=>2, "y" =>3, "z" => 4], ["x"=>20, "y" =>30, "z" => 40])) ==
            Flowstar._order_string(AdaptiveTMOrder( ("x" => (2,20), "y" => (3,30), "z" => (4,40)) )) == 
            Flowstar._order_string(AdaptiveTMOrder( ["x" => (2,20), "y" => (3,30), "z" => (4,40)] )) == 
            Flowstar._order_string(AdaptiveTMOrder( [:x => (2,20), :y => (3,30), :z => (4,40)] ))
            "adaptive orders { min {x :2 , y :3 , z :4} , max {x :20 , y :30 , z :40}}"
