### ISSUE TITLE
0 Flowpipe Handling

### ISSUE THREAD

**Issue by agerlach** [agerlach/Flowstar.jl#9]
Gracefully handle flowstar calls that return 0 flow pipes, i.e. when the follow occurs

> Computation not completed: 0 flowpipe(s) computed. 
Please try smaller step sizes or larger Taylor model orders.

Currently this produces a parsing error that is hard to decipher.

**Comment by mforets** [comment]
As you do in https://github.com/agerlach/Flowstar.jl/issues/9 looks good to me
